print("******************")
print("Hamburguesas el corral")
print("******************")
nombreUsuario=input("Digite el nombre del usuario: ")
cedulaUsuario = input("digite su cedula: ")
pedidoUsuario = input("Que hamburguesa va a pedir: ")
valorPedido = int(input("Valor del pedido: "))
cantidadPedido = int(input("Cuantas hamburguesas va a pedir: "))
print("******************")
print("******************")
print("******************")

print(pedidoUsuario)
print(cantidadPedido)
print(valorPedido*cantidadPedido)
